//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiddlewareWCF.JavaEEService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://facade.messagemgmt.checker.com/", ConfigurationName="JavaEEService.CheckerEndpoint")]
    public interface CheckerEndpoint {
        
        // CODEGEN : Le paramètre 'checkedMessage' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://facade.messagemgmt.checker.com/CheckerEndpoint/checkOperationRequest", ReplyAction="http://facade.messagemgmt.checker.com/CheckerEndpoint/checkOperationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(checkOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(checkOperation))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="checkedMessage")]
        MiddlewareWCF.JavaEEService.checkOperationResponse1 checkOperation(MiddlewareWCF.JavaEEService.checkOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://facade.messagemgmt.checker.com/CheckerEndpoint/checkOperationRequest", ReplyAction="http://facade.messagemgmt.checker.com/CheckerEndpoint/checkOperationResponse")]
        System.Threading.Tasks.Task<MiddlewareWCF.JavaEEService.checkOperationResponse1> checkOperationAsync(MiddlewareWCF.JavaEEService.checkOperationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facade.messagemgmt.checker.com/")]
    public partial class msg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool opStatusField;
        
        private string infoField;
        
        private object[] dataField;
        
        private string operationNameField;
        
        private string appTokenField;
        
        private string userTokenField;
        
        private string appVersionField;
        
        private string operationVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool opStatus {
            get {
                return this.opStatusField;
            }
            set {
                this.opStatusField = value;
                this.RaisePropertyChanged("opStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
                this.RaisePropertyChanged("info");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public object[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string operationName {
            get {
                return this.operationNameField;
            }
            set {
                this.operationNameField = value;
                this.RaisePropertyChanged("operationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string appToken {
            get {
                return this.appTokenField;
            }
            set {
                this.appTokenField = value;
                this.RaisePropertyChanged("appToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string userToken {
            get {
                return this.userTokenField;
            }
            set {
                this.userTokenField = value;
                this.RaisePropertyChanged("userToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string appVersion {
            get {
                return this.appVersionField;
            }
            set {
                this.appVersionField = value;
                this.RaisePropertyChanged("appVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string operationVersion {
            get {
                return this.operationVersionField;
            }
            set {
                this.operationVersionField = value;
                this.RaisePropertyChanged("operationVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facade.messagemgmt.checker.com/")]
    public partial class checkOperationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool checkedMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool checkedMessage {
            get {
                return this.checkedMessageField;
            }
            set {
                this.checkedMessageField = value;
                this.RaisePropertyChanged("checkedMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facade.messagemgmt.checker.com/")]
    public partial class checkOperation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private msg messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public msg message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkOperation", WrapperNamespace="http://facade.messagemgmt.checker.com/", IsWrapped=true)]
    public partial class checkOperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facade.messagemgmt.checker.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MiddlewareWCF.JavaEEService.msg message;
        
        public checkOperationRequest() {
        }
        
        public checkOperationRequest(MiddlewareWCF.JavaEEService.msg message) {
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkOperationResponse", WrapperNamespace="http://facade.messagemgmt.checker.com/", IsWrapped=true)]
    public partial class checkOperationResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facade.messagemgmt.checker.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool checkedMessage;
        
        public checkOperationResponse1() {
        }
        
        public checkOperationResponse1(bool checkedMessage) {
            this.checkedMessage = checkedMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CheckerEndpointChannel : MiddlewareWCF.JavaEEService.CheckerEndpoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckerEndpointClient : System.ServiceModel.ClientBase<MiddlewareWCF.JavaEEService.CheckerEndpoint>, MiddlewareWCF.JavaEEService.CheckerEndpoint {
        
        public CheckerEndpointClient() {
        }
        
        public CheckerEndpointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CheckerEndpointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckerEndpointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckerEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MiddlewareWCF.JavaEEService.checkOperationResponse1 MiddlewareWCF.JavaEEService.CheckerEndpoint.checkOperation(MiddlewareWCF.JavaEEService.checkOperationRequest request) {
            return base.Channel.checkOperation(request);
        }
        
        public bool checkOperation(MiddlewareWCF.JavaEEService.msg message) {
            MiddlewareWCF.JavaEEService.checkOperationRequest inValue = new MiddlewareWCF.JavaEEService.checkOperationRequest();
            inValue.message = message;
            MiddlewareWCF.JavaEEService.checkOperationResponse1 retVal = ((MiddlewareWCF.JavaEEService.CheckerEndpoint)(this)).checkOperation(inValue);
            return retVal.checkedMessage;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiddlewareWCF.JavaEEService.checkOperationResponse1> MiddlewareWCF.JavaEEService.CheckerEndpoint.checkOperationAsync(MiddlewareWCF.JavaEEService.checkOperationRequest request) {
            return base.Channel.checkOperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiddlewareWCF.JavaEEService.checkOperationResponse1> checkOperationAsync(MiddlewareWCF.JavaEEService.msg message) {
            MiddlewareWCF.JavaEEService.checkOperationRequest inValue = new MiddlewareWCF.JavaEEService.checkOperationRequest();
            inValue.message = message;
            return ((MiddlewareWCF.JavaEEService.CheckerEndpoint)(this)).checkOperationAsync(inValue);
        }
    }
}
